#!/bin/sh
DIR="/usr/local/firefox/"
BROWSER="$DIR/firefox"
MOZ_CLIENT_PROGRAM="$DIR/mozilla-xremote-client"

#LOG="/tmp/firefox-$$.txt"
#echo $@ > $LOG
check_running() {
    $MOZ_CLIENT_PROGRAM -a firefox 'ping()' 2>/dev/null >/dev/null
    RETURN_VAL=$?
    if [ $RETURN_VAL -eq 0 ]; then
        echo 1
        return 1
    else
        echo 0
        return 0
    fi
}

if [ `check_running` -eq 1 ]; then
    exec $MOZ_CLIENT_PROGRAM -a firefox "openURL($@,new-tab)"
else
    #echo "Falling back"
    exec $BROWSER $@
fi
