build_test_fork_sid:
	cc -o test_fork_sid test_fork_sid.c

clean_test_fork_sid:
	rm -f test_fork_sid

build_test_daemon:
	cc -o test_daemon test_daemon.c

clean_test_daemon:
	rm -f test_daemon

.PHONY: build_test_fork_sid clean_test_fork_sid
