#!/usr/bin/ruby
# Luis Mondesi <lemsx1@gmail.com> 
# 2010-06-14 13:36 EDT 
#
# a simple script to encrypt to a list of GPG users given by recipients
#
# Sample Recipients File created with: gpg -k --with-colons | grep '^pub' > recipients
# pub:u:1024:17:5C1814A42C53C3DF:2007-10-09:::u:Luis Mondesi (UNIX SysAdmin) <lmondesi@fotolog.com>::scaESCA:
# pub:f:1024:17:CD2548594C516AF9:2002-01-16:::f:Luis Mondesi <lemsx1@gmail.com>::scESC:

def usage(e=1)
    puts "Usage: encrypt-to-recipients <recipients> <file>"
    exit e
end

r = ARGV[0]
f = ARGV[1]

r.nil? and usage 1
f.nil? and usage 1

test ?r, r or usage 2
test ?r, f or usage 2

recipients = Array.new

open(r).each_line do |l|
    recipients << l.split(/:/)[4]
end

args = " -r " + recipients.join(" -r ")

`gpg #{args} -e #{f}`
