#!/bin/sh
echo 'run to show all files:'
echo 'defaults write com.apple.finder AppleShowAllFiles TRUE;killall Finder'
echo 'run to hide all files:'
echo 'defaults write com.apple.finder AppleShowAllFiles FALSE;killall Finder'
