#!/bin/sh
git filter-branch --env-filter '

an="$GIT_AUTHOR_NAME"
am="$GIT_AUTHOR_EMAIL"
cn="$GIT_COMMITTER_NAME"
cm="$GIT_COMMITTER_EMAIL"

if [ "$GIT_COMMITTER_EMAIL" = "EMAIL_TO_CHANGE_FROM_HERE" ]
then
cn="Luis Mondesi"
cm="lemsx1@gmail.com"
fi
if [ "$GIT_AUTHOR_EMAIL" = "EMAIL_TO_CHANGE_FROM_HERE" ]
then
an="Luis Mondesi"
am="lemsx1@gmail.com"
fi

export GIT_AUTHOR_NAME=$an
export GIT_AUTHOR_EMAIL=$am
export GIT_COMMITTER_NAME=$cn
export GIT_COMMITTER_EMAIL=$cm
'
