#! /bin/sh

if [ ! -f /usr/sbin/ntpdate ]; then
    echo " no ntpdate "
    exit 0
fi

#. /etc/default/ntp-servers
NTPSERVERS="pool.ntp.org 208.184.49.9 131.107.1.10"
test -n "$NTPSERVERS" || exit 0

case "$1" in
start|restart|force-reload)
  echo -n "Running ntpdate to synchronize clock"
  /usr/sbin/ntpdate -u -b -s $NTPSERVERS
  echo "."
  ;;
stop)
  ;;
*)
  echo "Usage: /etc/init.d/ntpdate {start|stop|restart|force-reload}"
  exit 1
esac

exit 0
