#!/bin/sh
# Luis Mondesi <lmondesi@bloomberg.net>
# 2012-07-30
#
# . ssh-agent-setup from bashrc-`hostname`
#
# License: GPL

SSH_AUTH_SOCK=`find /tmp -uid $UID -name "agent.[0-9]*" -print 2> /dev/null|sort|tail -1`

clean_old_sock()
{
    rm -f $SSH_AUTH_SOCK
    rmdir /tmp/ssh-* > /dev/null 2>&1
}

launch_agent()
{
    eval `ssh-agent -s`
}

load_keys()
{
    for key in ~/.ssh/id_[rd]sa*; do
        if echo $key | egrep -q '\.pub$'; then
            continue
        fi
        ssh-add $key
        rc=$?
        if [ $rc = 2 ]; then
            echo "Repairing ssh-agent ($rc)"
            clean_old_sock
            launch_agent
            ssh-add $key
        elif [ $rc = 1 ]; then
            echo "Your key $key could not be loaded"
        fi
    done
}

if [ -S "$SSH_AUTH_SOCK" ]; then
    SSH_AGENT_PID=`echo $SSH_AUTH_SOCK|cut -d. -f2`
    export SSH_AUTH_SOCK SSH_AGENT_PID
fi
load_keys
