#!/bin/sh
# Luis Mondesi <lmondesi@bloomberg.net>
# 2012-07-30
#
# . ssh-agent-setup from bashrc-`hostname`
#
# License: GPL

if [ ! -S $SSH_AUTH_SOCK ]; then
    SSH_AUTH_SOCK=`find /tmp -uid $UID -name "agent.[0-9]*" -print 2> /dev/null|sort|tail -1`
    if [ ! -S $SSH_AUTH_SOCK ]; then
        SSH_AUTH_SOCK=`find /var/folders -uid $UID -name "agent.[0-9]*" -print 2> /dev/null|sort|tail -1`
    fi
fi

if [ -S $SSH_AUTH_SOCK ]; then
    echo export SSH_AUTH_SOCK=$SSH_AUTH_SOCK

    SSH_AGENT_PID=`echo $SSH_AUTH_SOCK|cut -d. -f2`
    echo export SSH_AGENT_PID=$SSH_AGENT_PID
fi

clean_old_sock()
{
    rm -f $SSH_AUTH_SOCK
    rmdir /tmp/ssh-* > /dev/null 2>&1
}

launch_agent()
{
    eval `ssh-agent -s`
}

load_keys()
{
    for key in ~/.ssh/id_[rd]sa* ~/.ssh/*/id_[rd]sa*; do
        echo "# Loading $key"
        if echo $key | egrep -q '\.pub$'; then
            continue
        fi
        ssh-add $key
        rc=$?
        if [ $rc = 2 ]; then
            echo "# Repairing ssh-agent ($rc)"
            clean_old_sock
            launch_agent
            ssh-add $key
        elif [ $rc = 1 ]; then
            echo "# Your key $key could not be loaded"
        fi
    done
}

if [ -S "$SSH_AUTH_SOCK" ]; then
    export SSH_AUTH_SOCK SSH_AGENT_PID
    if [ $(ssh-add -l|wc -l) -lt 1 ]; then
        rm -f $SSH_AUTH_SOCK; rmdir `dirname $SSH_AUTH_SOCK`
        echo "starting new ssh-agent"
        eval `ssh-agent -s`
        load_keys
    else
        echo "# Re-using agent $SSH_AUTH_SOCK"
    fi
else
    load_keys
fi
