#!/bin/sh
# "Luis Mondesi <lemsx1@gmail.com>"  
#  2011-03-03 09:59 EST
#
# . ssh-agent-setup from bashrc-`hostname`
#
# License: GPL

SSH_AUTH_SOCK=`find /tmp -name "agent.[0-9]*" -print|sort|tail -1`

if [ -S "$SSH_AUTH_SOCK" ]; then
    SSH_AGENT_PID=`echo $SSH_AUTH_SOCK|cut -d. -f2`
    export SSH_AUTH_SOCK SSH_AGENT_PID
else
    echo executing ssh-agent -s
    eval `ssh-agent -s`
fi
ssh-add
if [ $? != 0 ]; then
    # apparently ssh-agent died without cleaning a socket?
    if [ -e "$SSH_AUTH_SOCK" ]; then
        rm -f $SSH_AUTH_SOCK; unset SSH_AUTH_SOCK SSH_AGENT_PID
        rmdir /tmp/ssh-*
    fi
    echo repairing ssh-agent
    eval `ssh-agent -s`
    ssh-add
    if [ $? != 0 ]; then
        echo Please launch "eval 'ssh-agent -s'" manually > /dev/stderr
    fi
fi
