"
" /etc/gvimrc
"
" edited by Luis Mondesi <lemsx1@gmail.com> 
" Version: 2005-04-25 11:42 EDT 

set guipty

" full mouse mode here :-)
set mouse=a

" Hide the mouse pointer while typing
set mousehide
" windows focus follows mouse pointer
"set mousefocus

" Switch syntax highlighting on, when the terminal has colors
" (this is probably already done by vimrc, but just in case...)
if &t_Co > 2 || has("gui_running")
  syntax on
  :colorscheme peachpuff
  " let's set better colors for the folding characters
  :hi FoldColumn term=standout ctermfg=4 ctermbg=7 guifg=#ff8060 guibg=PeachPuff
  " :colorscheme default
  " Set a reasonable font
  "set guifont=6x10
  " in MacVim select a font with:
  "set guifont=*
  " Example:
  set guifont=Menlo:h18,DejaVu\ Sans\ Mono:h13
endif

" open a big window please
set lines=50
set columns=180

