#!/bin/sh
# $Revision: 1.3 $
# $Date: 2007-03-01 21:41:46 $
# my_name < email@example.com >
#
# DESCRIPTION:
# USAGE:
# LICENSE: ___

for i in *.jar; do
    rm -fr $i.dir
    mkdir $i.dir || exit 1
    cd $i.dir || exit 2
    jar -xf ../$i
    PATCH=`echo $i|sed s/\.jar$//`
    if [ -d $PATCH ]; then
        chmod u+rx $PATCH/*
        patchadd -d $PATCH
        if [ $? = 0 ]; then
            cd ..
            rm -fr $i.dir
        else
            echo "patchadd -d $PATCH could not install $i. Exit code $?"
            exit 3
        fi  
    else
        echo "Sorry, $PATCH directory does not exist for $i"
        exit 4
    fi
done
