#!/bin/bash
# Luis Mondesi <lemsx1@gmail.com> 
# 2008-12-22 11:15 EST 
#
# DESCRIPTION: fix the resource fork for Mac files by copying a new resource from a good file
# USAGE: Usage: $0 'good file' 'bad file'
# LICENSE: GPL
# 
# BUGS: Needs XCode Tools installed in /Developers

USAGE="Usage: $0 'good file' 'bad file'"

function print_error
{
    echo "ERROR: $*"
}

if [ `uname -s` != "Darwin" ]; then
    echo "This is not a Mac!"
    exit 1
fi

if [ -z "$1" ] || [ -z "$2" ]; then
    echo $USAGE
    exit 1
fi

if [ ! -r "$1" ]; then
    print_error "Error: Cannot read file name '$1'"
    exit 1
fi

if [ ! -r "$2" ]; then
    print_error "Error: Cannot read file name '$2'"
    exit 1
fi

echo "Fixing resource forks on current directory"

TMPDIR="tmpdir$RANDOM"

if [ -d $TMPDIR ]; then
    print_error "TMPDIR already exist? Exiting..."
    echo "Please run the command again and examine $TMPDIR"
    exit 2
fi

mkdir $TMPDIR
cp $1 $2 $TMPDIR

cd $TMPDIR

/Developer/Tools/SplitForks $1

cp ._$1 ._$2

rm -f ._$1 $1

/System/Library/CoreServices/FixupResourceForks .

if [ $? = 0 ]; then
    cp $2 ../
else
    print_error "FixupResourceForks failed?"
fi

# cleanup
cd ..
rm -fr $TMPDIR
