#!/usr/bin/perl -w
#
# Luis Mondesi <lemsx1@gmail.com>
#
# DESCRIPTION:
# Use this to add a file or series of files to
# CVS in one shot!
#
# USAGE: cvsadd filename [filename ...]
#
# LICENSE: GPL
#
# Changelog:
# 2003-09-27 04:53 EDT made silent
# 2005-09-25 18:02 EDT much more efficient

$|++;
use strict;
use Getopt::Long;
Getopt::Long::Configure('bundling');

my $DEBUG = 0;
my $INCLUDE_DIRS=0;
my $EXCEPTIONS_REGEX = "(.*\.swp\$|.*\.o\$|.*\.so\$)";
my @FILES = ();

GetOptions(
    # flags
#    'v|version'         =>  \$PVERSION,
#    'h|help'            =>  \$HELP,
    'D|debug'           =>  \$DEBUG,
    'd|include-dirs'    =>  \$INCLUDE_DIRS,
    # strings
    #'o|option=s'       =>  \$NEW_OPTION,
    # numbers
    #'a|another-option=i'      =>  \$NEW_ANOTHER_OPTION,
);

sub is_image
{
    # returns 1 if true
    my $file = shift;
    print STDERR ( "is_image() called: $file\n" ) if ( $DEBUG );
    my $file_t = qx/file "$file"/;
    if ( $file_t =~ m/(\bGIF\b|\bPNG\b|\bJPEG\b)/i )
    {
        return 1;
    }
    print STDERR ( "not image file\n" ) if ( $DEBUG );
    return 0;
}

sub is_binary
{
    # returns 1 if true
    my $file = shift;
    print STDERR ( "is_binary() called: $file\n" ) if ( $DEBUG );
    my $file_t = qx/file "$file"/;
    if ( $file_t =~ m/(text\s+executable|\btext\b)/i )
    {
        return 0;
    }
    print STDERR ( "binary file\n" ) if ( $DEBUG );
    return 1;
}

if ( defined($ARGV[0]) and -f $ARGV[0] )
{
    @FILES = @ARGV;    
} else {
    my $addlist = qx/cvs update/;
    for my $i ( split(/\n/,$addlist) )
    {
        next if ($i !~ /^\s*\?/g); # if not a new file, keep on
        $i =~ s/^\s*\?\s*//;    # remove ? from the beginning of the line
        push(@FILES,$i);        # files will be tested later
    }
}

for my $file (@FILES)
{
    if (    ! -f $file
            and ! is_image($file)
            and ( is_binary($file) or $file =~ /$EXCEPTIONS_REGEX/ )
        )
        {
            unless ( $INCLUDE_DIRS )
            {
                print STDERR ("Skipping file «$file»\n");
                next;
            }
    }
    system("cvs add $file 2> /dev/null");
    if ( $? == 0 )
    {
        system( "cvs commit -m 'first commit' $file" );
    } else {
        print STDERR ("Error adding «$file» to the repository\n");
    }
}
