#!/bin/sh
# FIXME: this is quick and dirty; replace with a more robust script snippet
# from the security.debian.org documentation
if [ `uname -s` = 'linux' ]; then
    for i in `sudo lsof -i | grep LISTEN | cut -d " " -f 1 |sort -u` ; do
        pack=`dpkg -S $i |grep bin |cut -f 1 -d : | uniq`
        echo "Service $i is installed by $pack";
        init=`dpkg -L $pack |grep init.d/ `
        if [ ! -z "$init" ]; then
            echo "and is run by $init"
        fi
    done
else
    netstat -na
fi
