#!/usr/bin/perl -w
# $Revision: 1.2 $
# $Date: 2005-10-15 13:06:02 $
# Luis Mondesi < lemsx1@gmail.com >
#
# DESCRIPTION: converts a UNIX epoc timestamp to local time date
# USAGE: epoch2date SECONDS_SINCE_JAN_1_1970
# LICENSE: GPL

use strict;
$|++;

my $revision = "1.0"; # version

# standard Perl modules
use Getopt::Long;
Getopt::Long::Configure('bundling');
use File::Spec::Functions;  # abs2rel() and other dir/filename specific

# Args:
my $PVERSION=0;
my $HELP=0;
my $DEBUG=0;
# get options
GetOptions(
    # flags
    'v|version'         =>  \$PVERSION,
    'h|help'            =>  \$HELP,
    'D|debug'           =>  \$DEBUG,
    # strings
    #'o|option=s'       =>  \$NEW_OPTION,
    # numbers
    #'a|another-option=i'      =>  \$NEW_ANOTHER_OPTION,
);

if ( $HELP ) { 
    use Pod::Text;
    my $parser = Pod::Text->new (sentence => 0, width => 78);
    $parser->parse_from_file($0,\*STDOUT);
    exit 0;
}

if ( $PVERSION ) { print STDOUT ($revision); exit 0; }

my $seconds = join(" ",@ARGV);
$seconds =~ s/[^0-9\.]//g;
print "DEBUG: $seconds\n" if ( $DEBUG );
my $date = localtime($seconds);
print "$date\n"; 

__END__

=head1 NAME

epoch2date - epoch2date script for Perl

=head1 SYNOPSIS

B<epoch2date>  [-v,--version]
                [-D,--debug] 
                [-h,--help]

=head1 DESCRIPTION 

    This script ...

=head1 OPTIONS

=over 8

=item -v,--version

prints version and exits

=item -D,--debug

enables debug mode

=item -h,--help

prints this help and exits

=back

=head1 AUTHOR

Luis Mondesi <lemsx1@gmail.com>

=cut

