#!/bin/bash
# Delete a branch both local and in the remote repo
# This assumes you actually merged this to 'main' (or master) and
# it won't stop you
#
# Usage: gitbranchdelete BRANCH_NAME
#
# Luis Mondesi <lemsx1@gmail.com>
# License: GPL

if [[ -x `command -v git` ]]; then
    if git checkout main 2> /dev/null || git checkout master; then
        git branch -d $1
        git push origin --delete $1
        git remote prune origin
    else
        echo "No 'main' (or 'master') branch" >> /dev/stderr
        exit 1
    fi
else
    echo "Git command missing" >> /dev/stderr
    exit 1
fi
