#!/usr/bin/env ruby
#
# Luis Mondesi <lemsx1@gmail.com> 
# 2024-05-02
# LICENSE: GPL
#
# Makes my life easier to do a 'git checkout' by:
#
# 1. allowing me to paste one or more URLs, plus text, and figure out the name for this branch
# 2. create a new branch from the current branch (say 'main')
# 3. push this new branch to origin and,
# 4. set a remote tracker for it
#
# If a remote branch of the same name exists, then it will simply checkout a tracking branch locally
#
# Example:
#    gitcheckout https://foo/browse/PROJECT-851 cloud customer rejection
#    
#    git checkout -b project-851_cloud_customer_rejection
#    git push -u origin project-851_cloud_customer_rejection

# given an array of strings, create a valid branch name
# example: $0 http://foo/bar this is bar for TICKET_NUMBER -> 'bar_this_is_bar_for_TICKET_NUMBER'.downcase
def branch_name(args)
  name = ''
  args.each do |str|
    name += '_%s' % [str.gsub(/^.*\//,'').gsub(/\?.*$/,'')]
  end
  name.gsub(/^_/,'').downcase
end

def git_push_u(name)
  cmd = "git push -u origin #{name}"
  puts cmd
  out = `#{cmd}`
  if $? == 0
    # nothing
  else
    $stderr.puts "ERROR: failed to push '#{name}' to origin"
  end
end

# perform a git checkout usign the current branch as base to fork from
# then push to origin and set remote tracking for it
def git_checkout_and_push_u(name, opts={})
  # check if we have a remote branch already with this name,
  system "git fetch origin #{name}" # silently try to fetch this
  if `git branch -rl '*#{name}'`.strip == "origin/#{name}"
    cmd = "git checkout -b #{name} origin/#{name}"
    puts cmd
    out = `#{cmd}`
    if $? == 0
      git_push_u(name)
    else
      $stderr.puts "ERROR: failed to checkout '#{name}'"
    end
  else
    # if no, create one
    cmd = "git checkout -b #{name}"
    puts cmd
    out = `#{cmd}`
    if $? == 0
      git_push_u(name)
    else
      $stderr.puts "ERROR: failed to checkout '#{name}'"
    end
  end
end

name = branch_name(ARGV)
#p name # debug
git_checkout_and_push_u name
