#!/bin/bash
#
# Given a string, use `git grep STRING` to find all files where this is present, and then
# pass the resulting filenames to Vim for editing
#
# export EDITOR=gvim # mvim, neovim, or any other tool
#

if [[ -z "$EDITOR" ]]; then
    echo "ERROR: Environment variable \$EDITOR=$EDITOR not defined"
    echo "       export EDITOR=macvim"
    exit 1
fi

$EDITOR $(git grep "$*"|awk -F: '{print $1}'|uniq)
