#!/bin/bash
#
# Given a string, use `git grep STRING` to find all files where this is present, and then
# pass the resulting filenames to Vim for editing
#
# export EDITOR=gvim # mvim, neovim, or any other tool
#

if [[ -z "$EDITOR" ]]; then
    echo "ERROR: Environment variable \$EDITOR=$EDITOR not defined"
    echo "       export EDITOR=macvim"
    exit 1
fi
if [[ -z "$1" || -n "$2" ]]; then
    echo "Usage: $(basename $0) <STRING>"
    exit 1
fi

ARGS=""
if [[ $EDITOR =~ 'vim' ]]; then
  # after opening files in Vim, place cursor in the first instance of this pattern
  ARGS="+/$1"
fi

$EDITOR $ARGS $(git grep "$1"|awk -F: '{print $1}'|uniq)
