#!/bin/bash
#
# Given a string, use `git grep STRING` to find all files where this is present, and then
# pass the resulting filenames to $EDITOR for editing. If `vim` is used, it will highlight
# the string and move the cursor to the first instance in the first file opened.
#
# export EDITOR=gvim # mvim, neovim, or any other tool
#
# Luis Mondesi
# License: GPLv2

if [[ -z "$EDITOR" ]]; then
    echo "ERROR: Environment variable \$EDITOR=$EDITOR not defined"
    echo "       export EDITOR=macvim"
    exit 1
fi
if [[ -z "$1" || -n "$2" ]]; then
    echo "Usage: $(basename $0) <STRING>"
    exit 1
fi

ARGS=""
if [[ $EDITOR =~ 'vim' ]]; then
  # after opening files in Vim, place cursor in the first instance of this pattern
  ARGS="+/$1"
fi

files=$(git grep -l "$1")
if [[ -n $files ]]; then
    $EDITOR $ARGS $files
else
    echo No files found matching $1
fi
