#!/bin/sh
# Luis Mondesi <lemsx1@gmail.com> 
# LICENSE: GPL
# DESCRIPTION: A simple way to create an HTML index from files relative to this directory
USAGE="Usage:\n `basename $0` <list>\n Example: `basename $0` *.gif\n"
if [ -n "$1" ]; then
    printf "<html>\n\n"
    for i in $*; do
        case $i in
            *.gif|*.png|*.jpg)
                printf "\t\t<a href='%s'><img src='%s' alt='%s'/></a>\n" $i $i $i
                ;;
            *)
                printf "\t\t<a href='%s'>%s</a>\n" $i $i
                ;;
        esac
        printf "\t<br />\n"
    done
    printf "</html>\n"
else
    printf "$USAGE"
fi

