#!/bin/sh
# $Revision: 1.1 $
# Luis Mondesi < lemsx1@gmail.com >
#
# DESCRIPTION: a simple way to list our history
# USAGE: lshistory [text_or_regex]
# LICENSE: GPL

if [ -z "$HISTFILE" ]; then
    if [ -r ~/.bash_history ]; then
        HISTFILE=~/.bash_history
        echo "using $HISTFILE now"
    else
        echo "no history file found in HISTFILE"
        exit 1
    fi
fi

# history doesn't work
if [ -n "$*" ]; then
    cat -n $HISTFILE | egrep $*
else
    cat -n $HISTFILE
fi
