#!/bin/sh
# Luis Mondesi < lemsx1@gmail.com >
# 
# DESCRIPTION: a simple way to list running processes
#

PS='ps -eo pid,user,rss,args'

if [ ! -z $1 ]; then
    $PS | grep PID | grep -v grep # put the header
    $PS | grep -v lsproc | grep -v PID | grep -v grep | grep  $1
else
    $PS | grep -v lsproc | grep -v grep 
fi
