#!/bin/sh
# Luis Mondesi < lemsx1@gmail.com >
# 
# DESCRIPTION: a simple way to list running processes
# USAGE: lsproc [process_name]
# LICENSE: GPL
#

PS='ps -eaf'
#o pid,user,rss,stat,args'
SORT='sort --key=3 --reverse --numeric-sort'

if [ ! -z $1 ]; then
    $PS | head -1 # put the header
    $PS | grep -v lsproc | grep -v PID | grep -v grep | grep  $1 | $SORT
else
    $PS | head -1 # put the header
    $PS | grep -v lsproc | grep -v PID | grep -v grep | $SORT
fi
