#!/usr/bin/perl -w
# $Revision: 1.1 $
# $Date: 2006-01-29 09:58:19 $
# Luis Mondesi < lemsx1@gmail.com >
#
# DESCRIPTION: easy repository builder
# USAGE:
# LICENSE: GPL

=pod

=head1 NAME

repository - repository builder script for Debian and/or Fedora

=head1 DESCRIPTION 

    This script can be used to build a repository for Linux distros quickly

=cut

use strict;
$|++;

my $revision = "1.0"; # version

# standard Perl modules
use Getopt::Long;
Getopt::Long::Configure('bundling');
use POSIX;                  # cwd() ... man POSIX
use File::Spec::Functions;  # abs2rel() and other dir/filename specific
use File::Copy;
use File::Find;     # find();
use File::Basename; # basename() && dirname()
use FileHandle;     # for progressbar

# Args:
my $PVERSION=0;
my $HELP=0;
my $USAGE=0;
my $DEBUG=0;
my $FUNCTION=undef; # add remove update
my $WORKDIR='/home/Shared';

=pod

=head1 SYNOPSIS

B<repository>  [-v,--version]
                [-D,--debug] 
                [-h,--help]
                [-U,--usage]
                <add|remove|update>

=head1 OPTIONS

=over 8

=item -v,--version

Prints version and exits

=item -D,--debug

Enables debug mode

=item -h,--help

Prints this help and exits

=item -U,--usage

Prints usage information and exits

=back

=cut

# get options
GetOptions(
    # flags
    'v|version'         =>  \$PVERSION,
    'h|help'            =>  \$HELP,
    'D|debug'           =>  \$DEBUG,
    'U|usage'           =>  \$USAGE,
    # strings
    #'o|option=s'       =>  \$NEW_OPTION,
    # numbers
    #'a|another-option=i'      =>  \$NEW_ANOTHER_OPTION,
) and $FUNCTION=shift;

if ( $HELP ) { 
    use Pod::Text;
    my $parser = Pod::Text->new (sentence => 0, width => 78);
    $parser->parse_from_file($0,\*STDOUT);
    exit 0;
}

if ( $USAGE || not defined ($FUNCTION) || $FUNCTION =~ /^\s*$/ ) { 
    use Pod::Usage;
    pod2usage(1);
    exit 0; # never reaches here
}

if ( $PVERSION ) { print STDOUT ($revision); exit 0; }

my $distro = qx/lsb_release -i/;
chomp($distro);
$distro =~ s#Distributor\s+ID:\s+##i;
$distro = lc($distro);

die("Please make sure lsb_release is installed and in our PATH\n") 
    if ( $distro =~ /^\s*$/ );

my $workdir = $WORKDIR."/$distro";
chdir($workdir) or die("Could not change into directory $workdir. $!\n");

if ($distro =~ /ubuntu|debian/i)
{
    my $cmd = "reprepro"; # TODO allow others to be configured from CLI
    my $cmd_args = "";

    # sanity checks
    die("No ${workdir}/conf/distributions file found. Reprepro is not installed correctly\n") 
        if (not -f "conf/distributions");
   
    # We read conf/distributions from reprepro to support .deb's for multiple distributions:
    # sarge, woody, etch, breezy, etc...
    # Then the directories in incoming would be split like:
    # incoming/$codename
    # Where codename is a name like the ones from above
    open(FILE,"<","conf/distributions") 
        or die("Could not read ${workdir}/conf/distributions file. $!\n");

    my @distributions = ();
    while(<FILE>)
    {
        if ( $_ =~ /Codename:[[:space:]]*([[:alnum:]]+)/i)
        {
            push(@distributions,$1);
        }
    }
    close(FILE);
   
    print STDERR ("Distributions in conf/distributions: ",join(" ",@distributions),"\n") 
        if ( $DEBUG );

    if ( $FUNCTION eq 'add' )
    {
        # adding all files in "incoming"
        # .changes:
        for(glob("incoming/*.changes"))
        {
            my $distrib = _get_distrib($_);
            system("reprepro -b . include $distrib $_");
            die("Error while including $_\n") if ($? != 0);
        }

        # .dsc:
        for(glob("incoming/*.dsc"))
        {
            my $distrib = _get_distrib($_);
            system("reprepro -b . includedsc $distrib $_");
            die("Error while including sources for $_\n") if ($? != 0);
        }

        # .deb for e/a distrib:
        foreach my $distrib (@distributions)
        {
            for(glob("incoming/$distrib/*.deb"))
            {
                system("reprepro -b . includedsc $distrib $_");
                die("Error while including sources for $_\n") if ($? != 0);
            }
        }
    }

} else {
    print STDERR ("Distribution $distro not supported\n");
    print STDERR ("is lsb_release installed? try: lsb_release -i\n");
}

sub _get_distrib
{
    my $file = shift;
    die("File $file not plain text\n") if (not -f $file);
    open(FILE,"<$file") or die("Could not open file $file for reading. $!\n");
    while(<FILE>)
    {
        if ( $_ =~ /Distribution:[[:space:]]+([[:alnum:]]+)/i )
        {
            return $1;
            last; # never reached
        }
    }
}

=pod

=head1 AUTHORS

Luis Mondesi <lemsx1@gmail.com>

=cut

