#!/usr/bin/perl -w
# $Revision: 1.1 $
# Luis Mondesi < lemsx1@gmail.com >
#
# DESCRIPTION: a simple script to reverse the order of arguments to be moved. This is useful for when you move something temporarily somewhere, and then go back in the command line history to put the file_or_dir back in the original destination... If you setup your .inputrc to act like vi, then you can do:
#   mv file tmp_directory/
#   ... do some stuff ...
#   ... hit the up arrow ...
#   ... hit ESC and SHIFT i ...
#   rmv file tmp_directory/
# USAGE: rmv destination_dir file_or_dir [file_or_dir ...]
# LICENSE: GPL

use strict;
$|++;

my $DEST=shift;

foreach($@)
{
#    system(mv $_ $DEST);
}
