#!/bin/sh
# Luis Mondesi <lemsx1@gmail.com>
# 2013-05-16
#
# sudo apt-get install git git-email
if [ -r ~/.signaturerc ]; then
    . ~/.signaturerc
fi
# use this script to tell Vim to use Mutt to send patches to your email
mkdir /tmp/patches.$$ || exit 1
git format-patch --to=${EMAIL:-$USER} -o /tmp/patches.$$/ -M origin/master || exit 2
git send-email /tmp/patches.$$ || exit 3
rm -fr /tmp/patches.$$
