#!/bin/sh
# $Revision: 1.4 $
# Luis Mondesi < lemsx1@hotmail.com >
# Last modified: 2003-Nov-11
#
# DESCRIPTION:  A simple script to output a signature
#               to a ~/.signature or STDOUT, controlled
#               from a ~/.signaturerc file
# USAGE:
# CHANGELOG:
#

# -- copy to .signaturerc from here -- #
NAME="Luis M"
POSITION="System Administrator/Web Developer"
COMPANY="LatinoMixed.com"
PHONE=""
EMAIL="lemsx1@latinomixed.com"
URL="http://www.latinomixed.com/"
DEFAULT_SIGNATURE="'We think basically you watch television to turn your brain off, and you work on your computer when you want to turn your brain on' -- Steve Jobs in an interview for MacWorld Magazine 2004-Feb"

SIGNATURE=1 # whether to generate a signature using fortunes
QUOTE=1
STDOUT=1
RECODE=1
EVOLUTION=1 # evolution requires sig to be in HTML <br>

FORTUNE_ARGS=" -s 50% computers 50% linux " # see "man fortune" for more

# -- end copy --#

# Now use that to create a ~/.signaturerc file
# per server
. "$HOME"/.signaturerc

ENDLINE="\n"

if [ $EVOLUTION -eq 1 -a $STDOUT -eq 1 ]; then
    ENDLINE="<br>"
else
    ENDLINE="\n"
fi

# signature header
if [ $STDOUT -eq 1 ]; then
    echo -e "--$ENDLINE----)(----- $ENDLINE $NAME $ENDLINE $POSITION $ENDLINE $COMPANY $ENDLINE $PHONE $ENDLINE $EMAIL $ENDLINE"
else
    echo -e "--$ENDLINE----)(----- $ENDLINE $NAME $ENDLINE $POSITION $ENDLINE $COMPANY $ENDLINE $PHONE $ENDLINE $EMAIL $ENDLINE" > "$HOME/.signature"
fi

# body
if [ -x "/usr/games/fortune" -a $QUOTE -eq 1 ]; then
    # makes our day a bit more fun.... :-)
    if [ $STDOUT -eq 1 ]; then
        if [ $RECODE -eq 1 -a -x "/usr/bin/recode" ];then
            /usr/games/fortune $FORTUNE_ARGS | /usr/bin/recode -q ISO-8859-1..utf-8
        else
            /usr/games/fortune $FORTUNE_ARGS
        fi
    else
        if [ $RECODE -eq 1 ];then
            /usr/games/fortune $FORTUNE_ARGS | /usr/bin/recode -q ISO-8859-1..utf-8 >> "$HOME/.signature"
        else
            /usr/games/fortune $FORTUNE_ARGS  >> "$HOME/.signature"

        fi
    fi
else
    # fall back to this default signature
    echo $DEFAULT_SIGNATURE >> "$HOME/.signature"
fi

# footer
if [ $STDOUT -eq 1 ]; then
    echo -e "$ENDLINE $ENDLINE $URL"
else
    echo -e "$ENDLINE $ENDLINE $URL" >> "$HOME/.signature"
fi
