#!/bin/sh
## Luis Mondesi <lemsx1@hotmail.com> 
## 2004-09-20 16:29 EDT 
## NOTE: using a socket improves speed
if [[ -S "/var/run/spamd" ]]; then
    spamc -U /var/run/spamd | /usr/sbin/sendmail -i "$@"
else
    # fallback to TCP/IP connection to port 783 on localhost
    spamc | /usr/sbin/sendmail -i "$@"
fi
exit $?
