#!/bin/bash
# Syncs all upstream repositories to this branch
# Luis Mondesi <lemsx1@gmail.com>
#
# License: GPL

if [[ -x $(command -v git) ]]; then
    for remote in $(git remote); do
        git pull $remote $(git branch|grep '^*'|head -1|awk '{print $NF}')
        git remote prune $remote
    done
    git push
else
    echo "git command not found"
    exit 1
fi
