#!/usr/bin/perl -w
# Luis Mondesi < lemsx1@hotmail.com >
# 
# DESCRIPTION: use this script to untar, unzip, unrar, etc...,
# a bunch of files with extensions: .tar.bz2, .tar.gz, .zip, .rar

use strict;
use File::Spec::Functions;

my $DEBUG = 0;

foreach my $i ( @ARGV )
{
    if ( -r $i )
    {
        # simple CASE/ESAC:
        ( $i =~ /(\.tar\.(g|b)z(ip2)*|\.t(g|b)z)$/i ) and _uncompress($i,'tar') and next; # /bin/uncompress could take care of this but not bzip2 files
        ( $i =~ /\.zip$/i ) and _uncompress($i,'unzip') and next;
        ( $i =~ /\.ra[[:alnum:]]+$/i ) and _uncompress($i,'unrar') and next;
        ( $i =~ /(\.gz|\-gz|\.z|\-z|\_z|.Z)$/i ) and _uncompress($i,'gunzip') and next;
    }
}

sub _uncompress
{
    my $file = shift;
    return undef if ( not defined $file );
    my $bin = shift;
    my $binary = which($bin);
    return undef if ( not defined $binary );
    
    my $args = "";
    # special cases:
    $args .= "xj" if ( $file =~ /(\.tar\.bz(ip2)*|\.tbz)$/i);
    $args .= "xz" if ( $file =~ /(\.tar\.gz|\.tgz)$/i);
    $args .= "f" if ( $file =~ /(\.tar\.(g|b)z(ip2)*|\.t(g|b)z)$/i);

    #SYSTEM:
    $file = escape_nonshell($file);
    print STDERR ($binary," ",$args," ",$file,"\n") if ( $DEBUG );
    system("$binary $args $file");
    return $?;
}

sub escape_nonshell
{
    my $str = shift;
    return undef if ( not defined $str );
    $str =~ s/([^[:alnum:]\_\-\.])/\\$1/g;
    return $str;
}

sub which 
{
    # @param 0 string := binary to find in $ENV{PATH}
    # @return binary path or undef
    my $binary = shift;
    my $path = undef;
    foreach my $binary_path ( split(/:/,$ENV{"PATH"}) )
    {
        $path = File::Spec->catfile($binary_path,$binary);
        last if ( -x $path );
    }
    return $path; # undef means not found
}
