#!/usr/bin/perl -w
# Luis Mondesi < lemsx1@hotmail.com >
# 
# DESCRIPTION: use this script to untar, unzip, unrar, etc...,
# a bunch of files with extensions: .tar.bz2, .tar.gz, .zip, .rar

foreach my $i ( @ARGV )
{
    if ( -r $i )
    {
        ( $i =~ /\.tar\.(g|b)z(ip2)*$|\.t(g|b)z$/i ) and untar($i) and next;
        ( $i =~ /\.zip$/i ) and unzip($i) and next;
        ( $i =~ /\.ra[[:alnum:]]+$/i ) and unrar($i) and next;
    }
}

sub unrar
{
    my $file = shift;
    return undef if ( not defined $file );
    system("unrar $file");
    return $?;
}

sub unzip
{
    my $file = shift;
    return undef if ( not defined $file );
    system("unzip $file");
    return $?;
}

sub untar
{
    my $file = shift;
    return undef if ( not defined $file );

    my $_util = ( $file =~ /bz/i) ? "j":"z";
    
    system("tar x".$_util."f $file");
    return $?;
}
