#!/usr/bin/perl
# Luis Mondesi <lemsx1@gmail.com>
# 2007-12-12 11:49 EST
#
# DESCRIPTION: a simple script that emulates 'watch' from Linux using Perl
# This is useful only on UNIX systems where 'watch' is missing (Solaris!)
# USAGE: watch <command>
# LICENSE: GPL

my $USAGE = 'Usage: watch <command>';

if (!$ARGV[0])
{
    print STDERR $USAGE . "\n";
    exit 1;
}

my $sleep = "2.0";

# can't we just use chr(27) some how?
#(-x '/usr/bin/clear') ? `clear` : "\n"x4;
my $_clear_char = `clear`;
my $_cmd = join(' ', @ARGV);

# display pretty status
my $_cmd_line = $_cmd;
my @split = split(//, $_cmd);
if (scalar @split > 32)
{
    $_cmd_line = substr($_cmd, 0, 16) . "...";
    $_cmd_line .= substr($_cmd, -16);
}
my $_status = "Every ${sleep}s: $_cmd_line\t\t";

while (1)
{
    print STDOUT ($_clear_char, $_status, scalar localtime(time()) . "\n\n");
    system($_cmd);
    sleep $sleep;
}
