#!/usr/bin/perl -w
use strict;
$|++;

use lib '/usr/local/lib/site_perl';

package main;

use Sys::Hostname qw/hostname/;
use XMLRPC::Lite;

my $DEBUG = 0;
my $USAGE = "$0 URL /path/to/file";

#/cgi-bin/xmlrpc-getip.cgi
my $URL  = $ARGV[0] or die("$USAGE\n");
my $FILE = $ARGV[1] or die("$USAGE\n");

open(FILE, "<",$FILE) or die("$USAGE\n $!\n");
my %db = ();
while (<FILE>)
{
    s/#.*//;     #  comments
    s/^\s+//;    #  whitespace before stuff
    s/\s+$//;    #  whitespace after stuff
    next unless length;    #  If our line is empty, we ignore it
    my ($var_name, $value) = split(/\s*=\s*/, $_, 2);
    $db{$var_name} = $value;
}
close(FILE);

my $server = XMLRPC::Lite->proxy($URL);

$db{'hostname'} = hostname() if (not exists($db{'hostname'}));

$server->call('Host.newIP', \%db);

exit 0;
